target("ISPCTextureCompressor")
    set_group("02.tools")
    set_policy("build.across_targets_in_parallel", false)
    set_kind("static")
    add_packages("ispc")
    add_rules("utils.ispc")
    add_files("src/**.ispc")

codegen_component("SkrTextureCompiler", { api = "SKR_TEXTURE_COMPILER", rootdir = "include/SkrTextureCompiler" })
    add_files("include/**.hpp")

shared_module("SkrTextureCompiler", "SKR_TEXTURE_COMPILER")
    set_group("02.tools")
    add_deps("ISPCTextureCompressor")
    public_dependency("SkrRenderer")
    public_dependency("SkrImageCoder")
    public_dependency("SkrToolCore")
    skr_unity_build()
    add_includedirs("include", {public=true})
    add_files("src/**.cpp")