shared_module("SkrPhysics", "SKR_PHYSICS")
    public_dependency("SkrRT")
    add_includedirs("include", {public=true})
    add_rules("c++.unity_build", {batchsize = default_unity_batch})
    add_files("src/**.cpp")