codegen_component("SkrRenderer", { api = "SKR_RENDERER", rootdir = "include/SkrRenderer" })
    add_files("include/**.h")
    add_files("include/**.hpp")

shared_module("SkrRenderer", "SKR_RENDERER")
    public_dependency("SkrScene")
    public_dependency("SkrRenderGraph")
    public_dependency("SkrImGuiNG")
    add_includedirs("include", {public=true})
    skr_unity_build()
    add_files("src/*.cpp")
    add_files("src/resources/*.cpp", {unity_group = "resources"})