codegen_component("SkrToolCore", { api = "TOOL_CORE", rootdir = "include/SkrToolCore" })
    add_files("include/**.h")
    add_files("include/**.hpp")

shared_module("SkrToolCore", "TOOL_CORE")
    set_group("02.tools")
    skr_unity_build()
    add_files("src/**.cpp")
    public_dependency("SkrRT")
    add_includedirs("include", {public = true})
    on_config(function (target, opt)
        target:add("defines", "SKR_RESOURCE_PLATFORM=u8\""..target:plat().."\"")
    end)

private_pch("SkrToolCore")
    add_files("src/pch.hpp")