// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SB.Core;

#nullable disable

namespace SB.Core.Migrations
{
    [DbContext(typeof(DependContext))]
    partial class DependContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("SB.Core.Depend", b =>
                {
                    b.Property<string>("TargetName")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("ExternalFileTimes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("InputArgs")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("InputFileTimes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("InputFiles")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TargetName");

                    b.ToTable("Depends");
                });
#pragma warning restore 612, 618
        }
    }
}
