shared_module("SkrInputSystem", "SKR_INPUTSYSTEM")
    add_rules("c++.unity_build", {batchsize = default_unity_batch})
    public_dependency("SkrRT")
    public_dependency("SkrInput")
    add_includedirs("include", {public=true})
    add_files("src/*.cpp")