// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

namespace SB.Core
{
    internal partial class JsonContext
    {
        private static readonly global::System.Text.Json.JsonEncodedText PropName_Version = global::System.Text.Json.JsonEncodedText.Encode("Version");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_Data = global::System.Text.Json.JsonEncodedText.Encode("Data");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_Source = global::System.Text.Json.JsonEncodedText.Encode("Source");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_ProvidedModule = global::System.Text.Json.JsonEncodedText.Encode("ProvidedModule");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_Includes = global::System.Text.Json.JsonEncodedText.Encode("Includes");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_ImportedModules = global::System.Text.Json.JsonEncodedText.Encode("ImportedModules");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_ImportedHeaderUnits = global::System.Text.Json.JsonEncodedText.Encode("ImportedHeaderUnits");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_directory = global::System.Text.Json.JsonEncodedText.Encode("directory");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_arguments = global::System.Text.Json.JsonEncodedText.Encode("arguments");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_file = global::System.Text.Json.JsonEncodedText.Encode("file");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_ExternalFiles = global::System.Text.Json.JsonEncodedText.Encode("ExternalFiles");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_Key = global::System.Text.Json.JsonEncodedText.Encode("Key");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_Value = global::System.Text.Json.JsonEncodedText.Encode("Value");
    }
}
