// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

namespace SB.Core
{
    internal partial class JsonContext
    {
        private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.List<global::System.Collections.Generic.KeyValuePair<string, global::System.DateTime>>>? _ListKeyValuePairStringDateTime;
        
        /// <summary>
        /// Defines the source generated JSON serialization contract metadata for a given type.
        /// </summary>
        #nullable disable annotations // Marking the property type as nullable-oblivious.
        public global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.List<global::System.Collections.Generic.KeyValuePair<string, global::System.DateTime>>> ListKeyValuePairStringDateTime
        #nullable enable annotations
        {
            get => _ListKeyValuePairStringDateTime ??= (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.List<global::System.Collections.Generic.KeyValuePair<string, global::System.DateTime>>>)Options.GetTypeInfo(typeof(global::System.Collections.Generic.List<global::System.Collections.Generic.KeyValuePair<string, global::System.DateTime>>));
        }
        
        private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.List<global::System.Collections.Generic.KeyValuePair<string, global::System.DateTime>>> Create_ListKeyValuePairStringDateTime(global::System.Text.Json.JsonSerializerOptions options)
        {
            if (!TryGetTypeInfoForRuntimeCustomConverter<global::System.Collections.Generic.List<global::System.Collections.Generic.KeyValuePair<string, global::System.DateTime>>>(options, out global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.List<global::System.Collections.Generic.KeyValuePair<string, global::System.DateTime>>> jsonTypeInfo))
            {
                var info = new global::System.Text.Json.Serialization.Metadata.JsonCollectionInfoValues<global::System.Collections.Generic.List<global::System.Collections.Generic.KeyValuePair<string, global::System.DateTime>>>
                {
                    ObjectCreator = () => new global::System.Collections.Generic.List<global::System.Collections.Generic.KeyValuePair<string, global::System.DateTime>>(),
                    SerializeHandler = ListKeyValuePairStringDateTimeSerializeHandler
                };
                
                jsonTypeInfo = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateListInfo<global::System.Collections.Generic.List<global::System.Collections.Generic.KeyValuePair<string, global::System.DateTime>>, global::System.Collections.Generic.KeyValuePair<string, global::System.DateTime>>(options, info);
                jsonTypeInfo.NumberHandling = null;
            }
        
            jsonTypeInfo.OriginatingResolver = this;
            return jsonTypeInfo;
        }

        // Intentionally not a static method because we create a delegate to it. Invoking delegates to instance
        // methods is almost as fast as virtual calls. Static methods need to go through a shuffle thunk.
        private void ListKeyValuePairStringDateTimeSerializeHandler(global::System.Text.Json.Utf8JsonWriter writer, global::System.Collections.Generic.List<global::System.Collections.Generic.KeyValuePair<string, global::System.DateTime>>? value)
        {
            if (value is null)
            {
                writer.WriteNullValue();
                return;
            }
            
            writer.WriteStartArray();

            for (int i = 0; i < value.Count; i++)
            {
                KeyValuePairStringDateTimeSerializeHandler(writer, value[i]);
            }

            writer.WriteEndArray();
        }
    }
}
